apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-config
  labels:
    app: helloworld-app
data:
  application.properties: |
    quarkus.http.host=0.0.0.0
    quarkus.http.port=8080
    quarkus.log.level=INFO
    quarkus.log.console.enable=true
    quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
    
    # Camel configuration
    camel.main.name=HelloWorldCamelK
    camel.component.http.connect-timeout=5000
    camel.component.http.socket-timeout=10000