apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: helloworld-app